file:
  tmpPath: tmp

aliyun-oss:
  endpoint: oss-cn-shenzhen.aliyuncs.com
  # 阿里云主账号AccessKey拥有所有API的访问权限，风险很高。强烈建议您创建并使用RAM账号进行API访问或日常运维，请登录 https://ram.console.aliyun.com 创建RAM账号。
  accessKeyId: LTAIqNp0CM3NfZZI
  accessKeySecret: VlI1PtrbVRyHbyCa5vQrnNqgS90RRv
  bucketName: consumer-images
  ossHost: http://oss.hepaicn.com