debug: true

spring:
  profiles:
    active: prd
  datasource:
    name: test
    url: jdbc:mysql://47.106.107.112:3306/sharing_space?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: Hepai2018
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
  mail:
    host: smtp.qq.com
    username: luo_iter@qq.com
    password: ycquuxnfoappbjai

## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.hepai.admin注意：对应实体类的路径
  type-handlers-package: com.hepai.admins.handlers



logging:
  config: classpath:log4j2.xml
  level:
    com.hepai.sharingspace.mapper: debug

server:
  port: 8080

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql


